services:
  fastapi:
    build: .
    container_name: "fastapi"
    restart: always
    volumes:
      - ./app:/code/app
    ports:
      - 8000:8000
    env_file:
      - .env

  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - .env