version: '3.7'

services:
  fastapi:
    build: .
    container_name: "fastapi"
    volumes:
      - ./app:/code/app
    ports:
      - 8000:8000
    env_file:
      - app/.env


  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: naxadb 
