services:
  fastapi:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    volumes:
      - .:/code
    depends_on:
      - db
    ports:
      - 8000:8000
    env_file:
      - .env
    networks:
      - fastapi-boilerplate

  db:
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./DockerData/postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - fastapi-boilerplate

networks:
  fastapi-boilerplate:
    driver: bridge