"""added permission on user table

Revision ID: 0560072843f5
Revises: a3afc20cfafd
Create Date: 2024-11-25 04:18:17.249487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0560072843f5'
down_revision: Union[str, None] = 'a3afc20cfafd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('permission', sa.Integer(), nullable=True, back_populates='user_permission'))
    op.create_foreign_key(None, 'user', 'permission', ['permission'], ['id'])
    op.drop_column('user', 'is_superuser')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'permission')
    # ### end Alembic commands ###
