"""added permission on user table

Revision ID: 0b2e69aa2675
Revises: f2d7cdd236e9
Create Date: 2024-11-25 04:36:27.834225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b2e69aa2675'
down_revision: Union[str, None] = 'f2d7cdd236e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
