"""added permission on user table

Revision ID: c42d6bac99ab
Revises: da21bc5a26f1
Create Date: 2024-11-25 05:29:39.963395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c42d6bac99ab'
down_revision: Union[str, None] = 'da21bc5a26f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_role_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_role_fkey', 'user', 'role', ['role'], ['id'])
    # ### end Alembic commands ###
