"""added permission on user table

Revision ID: da21bc5a26f1
Revises: 0b2e69aa2675
Create Date: 2024-11-25 05:24:26.612804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da21bc5a26f1'
down_revision: Union[str, None] = '0b2e69aa2675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_permission_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'permission_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_permission_id_fkey', 'user', 'permission', ['permission_id'], ['id'])
    # ### end Alembic commands ###
